" to ask for help in vim just type :h command or :h 'variable'

colo desert " color scheme

" print absolute line numbers
se nu     
se nornu 

se acd " change current open directory whenever you open a file or switch buffers

se ic " ignore case in search patterns
se sc " show partial command in the last line of the screen

" define shortcuts to compile and execute
aug cpp
    au!
    au FileType cpp map <f9> :w<CR> :!g++ -Wno-unused-result -D_GLIBCXX_DEBUG -Wconversion -Wshadow -Wall -Wextra -O2 -DLOCAL -std=c++17 -g3 "%" -o "%:p:r" <CR>
    au FileType cpp map <f5> :!"%:p:r" < a.in <CR>
    au FileType cpp map <f6> :!"%:p:r" <CR>
aug END 

" replace all tabs for 4 spaces
se ts=4
se sw=4
se sts=4
se et

se si " do smart autoindenting when starting a new line
se cin " enable automatic C program indenting

se cb=unnamedplus " share OS clipboard

se spr " split windows to the right

" no backups
se nobk
se nowb   
se noswf  


" color middle column
se cc=80

" switch between windows
nm <c-h> <c-w><c-h>
nm <c-j> <c-w><c-j>
nm <c-k> <c-w><c-k>
nm <c-l> <c-w><c-l>

" move around wrapped lines
map j gj
map k gk

" shift lines with < and >
vm > >gv
vm < <gv

" navigate buffers
nn <silent> [b :bp<CR>
nn <silent> ]b :bn<CR>
nn <silent> [B :bf<CR>
nn <silent> ]B :bl<CR>
